# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Easy' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Easy

pod 'Masonry', '~> 1.0.2'
pod 'SDWebImage', '~> 4.1.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'MJExtension', '~> 3.0.13'
pod 'JPFPSStatus', '~> 0.1' #FPS
pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'PPNetworkHelper', '~> 0.8.0'
pod 'JTSImageViewController', '~> 1.5.1'
pod 'JXPageView', '~> 1.1.2'
pod 'SDCycleScrollView', '~> 1.74'
pod 'BAButton', '~> 2.6.5'
pod 'IQKeyboardManager', '~> 5.0.6'
pod 'SVProgressHUD', '~> 2.2.2'
pod 'JXQRScan', '~> 1.0.5' # 二维码
# 微信
pod 'WechatOpenSDK'
pod 'YYImage', '~> 1.0.4'


#### >>>> 友盟
## U-Share SDK UI模块（分享面板，建议添加）
#pod 'UMengUShare/UI'
#
## 集成微信(精简版0.2M)
#pod 'UMengUShare/Social/ReducedWeChat'
#
## 集成QQ/QZone/TIM(精简版0.5M)
#pod 'UMengUShare/Social/ReducedQQ'
#
## 集成邮件
#pod 'UMengUShare/Social/Email'
#
## 集成短信
#pod 'UMengUShare/Social/SMS'



end
